# Názov tvojho workflow
name: Auto SFTP Deploy

# Kedy sa workflow spustí
on:
  push:
    # Spustí sa, keď sa pushne na vetvu 'master'
    branches: [ master ] 
    
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    # 1. Stiahne (checkout) kód z repozitára
    - name: Get latest code
      uses: actions/checkout@v4
      with:
        # KĽÚČOVÁ ZMENA: Stiahne celú históriu pre SFTP delta synchronizáciu
        fetch-depth: 0 

    # 2. Synchronizuje súbory na SFTP server
    - name: Sync files via SFTP
      uses: milanmk/actions-file-deployer@master 
      with:
        remote-protocol: "sftp"
        remote-host: ${{ secrets.FTP_SERVER }}
        remote-user: ${{ secrets.FTP_LOGIN }}
        remote-password: ${{ secrets.FTP_PASS }}
        
        local-path: './' 
        remote-path: './subdoms/client1/'
        
        # NOVÝ PARAMETER: Použite 'sync: delta' pre nahrávanie len zmenených súborov
        # Ak by ste chceli nahrať VŠETKY súbory, zmeňte na 'sync: full'
        sync: 'delta' 
        
        # ODSTRÁNENÝ: parameter sync-file bol neplatný